/**
 * QuickFlow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LearningSnapshot { 
    notStarted: number;
    inProgress: number;
    completed: number;
    milestonesDone: number;
    milestonesTotal: number;
}

