/**
 * QuickFlow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PlanUpdate { 
    title: string;
    estimatedDurationMinutes: number;
    startDateTime: string;
    endDateTime: string;
    priorityOrder: number;
}

