/**
 * QuickFlow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TaskTags { 
    /**
     * Each tag is trimmed first, then must be 1-30 characters (BR-T1); checked by the server, error field `tags`
     */
    tags: Array<string>;
}

